CREATE TABLE SIT.ID_TEST_TABLE
(
    ID    NUMBER NOT NULL,
    NAME  VARCHAR2(50 BYTE),
    VALUE NUMBER
)
    PCTUSED 0
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
(
    INITIAL 64K
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    BUFFER_POOL DEFAULT
)
    LOGGING
    NOCOMPRESS
    NOCACHE
    MONITORING;

CREATE UNIQUE INDEX SIT.ID_TEST_TABLE_PK ON SIT.ID_TEST_TABLE
    (ID)
    LOGGING
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (
    INITIAL 64 K
    NEXT 1 M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    BUFFER_POOL DEFAULT
    );

ALTER TABLE SIT.ID_TEST_TABLE
    ADD (
        CONSTRAINT ID_TEST_TABLE_PK
            PRIMARY KEY
                (ID)
                USING INDEX SIT.ID_TEST_TABLE_PK
                ENABLE VALIDATE);